import process from "process";
import { Router } from "express";
import { createClient } from "@supabase/supabase-js";

const router = Router();

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY,
);
import Groq from "groq-sdk";
const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

async function geminiSummarize(prompt) {
  const result = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [{ role: "user", content: prompt }],
  });
  return result.choices[0].message.content.trim();
}
// ─── Helpers ──────────────────────────────────────────────────────────────────

// ─── POST /api/admin/books ────────────────────────────────────────────────────
// Manually add a book
// Body: { title, author, description, cover_url, category, language,
//         page_count, published_year, google_book_id? }

router.post("/books", async (req, res) => {
  const {
    title,
    author,
    description,
    cover_url,
    category,
    language,
    page_count,
    published_year,
    google_book_id,
  } = req.body;

  if (!title || !author) {
    return res.status(400).json({ error: "title and author are required." });
  }

  const { data, error } = await supabase
    .from("books")
    .insert({
      title,
      author,
      description: description || null,
      cover_url: cover_url || null,
      category: category || null,
      language: language || "vi",
      page_count: page_count || null,
      published_year: published_year || null,
      google_book_id: google_book_id || null,
    })
    .select()
    .single();

  if (error) return res.status(500).json({ error: error.message });
  return res.status(201).json(data);
});

// ─── POST /api/admin/books/:bookId/chapters ───────────────────────────────────
// Add a chapter with content (summary auto-generated by Gemini)
// Body: { chapter_number, title, content }

router.post("/books/:bookId/chapters", async (req, res) => {
  const { bookId } = req.params;
  const { chapter_number, title, content } = req.body;

  if (!chapter_number || !title || !content) {
    return res
      .status(400)
      .json({ error: "chapter_number, title, and content are required." });
  }

  // Auto-generate summary with Gemini
  let summary = null;
  try {
    summary = await geminiSummarize(
      `Summarize the following book chapter in 3-5 sentences. Be concise and capture the key ideas. Write in the same language as the content.\n\nChapter: "${title}"\n\n${content.slice(0, 8000)}`,
    );
  } catch (err) {
    console.warn(
      "[admin] Gemini summary failed, saving without summary:",
      err.message,
    );
  }

  const { data, error } = await supabase
    .from("chapters")
    .insert({ book_id: bookId, chapter_number, title, content, summary })
    .select()
    .single();

  if (error) return res.status(500).json({ error: error.message });
  return res.status(201).json(data);
});

// ─── POST /api/admin/chapters/:chapterId/summarize ────────────────────────────
// Re-generate summary for an existing chapter

router.post("/chapters/:chapterId/summarize", async (req, res) => {
  const { chapterId } = req.params;

  const { data: chapter, error: fetchErr } = await supabase
    .from("chapters")
    .select("title, content")
    .eq("id", chapterId)
    .single();

  if (fetchErr) return res.status(404).json({ error: "Chapter not found." });

  try {
    const summary = await geminiSummarize(
      `Summarize the following book chapter in 3-5 sentences. Be concise and capture the key ideas. Write in the same language as the content.\n\nChapter: "${chapter.title}"\n\n${chapter.content.slice(0, 8000)}`,
    );

    const { data, error } = await supabase
      .from("chapters")
      .update({ summary })
      .eq("id", chapterId)
      .select()
      .single();

    if (error) throw error;
    return res.json({ chapter_id: chapterId, summary: data.summary });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ─── POST /api/admin/books/:bookId/summarize ──────────────────────────────────
// Generate whole-book summary from chapter summaries (Option A strategy)

router.post("/books/:bookId/summarize", async (req, res) => {
  const { bookId } = req.params;

  // Fetch book + all chapter summaries
  const { data: book, error: bookErr } = await supabase
    .from("books")
    .select("title, author")
    .eq("id", bookId)
    .single();

  if (bookErr) return res.status(404).json({ error: "Book not found." });

  const { data: chapters, error: chapErr } = await supabase
    .from("chapters")
    .select("chapter_number, title, summary, content")
    .eq("book_id", bookId)
    .order("chapter_number", { ascending: true });

  if (chapErr) return res.status(500).json({ error: chapErr.message });
  if (!chapters || chapters.length === 0) {
    return res
      .status(422)
      .json({ error: "No chapters found. Add chapters first." });
  }

  // Build context: prefer chapter summaries, fallback to first 500 chars of content
  const chapterContext = chapters
    .map((c) => {
      const text = c.summary || c.content?.slice(0, 500) || "";
      return `Chapter ${c.chapter_number} — ${c.title}:\n${text}`;
    })
    .join("\n\n");

  try {
    const book_summary = await geminiSummarize(
      `You are summarizing the book "${book.title}" by ${book.author}.

Below are summaries of each chapter. Write a comprehensive book summary in 5-8 sentences that:
- Captures the main thesis and key ideas
- Highlights the most important insights
- Is written for a reader deciding whether to read the book
- Uses the same language as the chapter summaries

Chapter summaries:
${chapterContext}`,
    );

    const { error: updateErr } = await supabase
      .from("books")
      .update({ book_summary })
      .eq("id", bookId);

    if (updateErr) throw updateErr;
    return res.json({ book_id: bookId, book_summary });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// ─── DELETE helpers (optional but useful) ────────────────────────────────────

router.delete("/books/:bookId", async (req, res) => {
  const { error } = await supabase
    .from("books")
    .delete()
    .eq("id", req.params.bookId);
  if (error) return res.status(500).json({ error: error.message });
  return res.json({ deleted: true });
});

router.delete("/chapters/:chapterId", async (req, res) => {
  const { error } = await supabase
    .from("chapters")
    .delete()
    .eq("id", req.params.chapterId);
  if (error) return res.status(500).json({ error: error.message });
  return res.json({ deleted: true });
});

export default router;
